### ISSUE TITLE
Ensembl annotation file 

### ISSUE THREAD

**Issue by cecileherbermann** [cfbuenabadn/sc_splicing_tools#1]
Hi Carlos,

A while ago I messaged you about the AssertionError I got when running Psix. The problem was that I was using Ensembl IDs in the TPM file while simultaneously using the provided hg38_introns.tab which contains gene names. I still got the error after changing the Ensembl IDs to gene names, but I also realized that many genes in my TPM files were not present in the annotation file. 
Therefore, I decided to create my own annotation file using GTF2psix. 

(a) However, the layout seems to be different from the example annotation that you provided and it contains a lot of 'other'. 
Overall, it does not seem to be completely correct and I was wondering what went wrong. This is the annotation file after running GTF2psix: [psix_annotation.tab.gz](https://github.com/lareaulab/psix/files/12291432/psix_annotation.tab.gz).
The GTF file that I used was downloaded from Ensembl: [Homo_sapiens.GRCh38.109.gtf](https://ftp.ensembl.org/pub/release-109/gtf/homo_sapiens/)

(b) Ideally, I would actually like to use Ensembl IDs instead of gene names for the annotation, since not every Ensembl ID has a gene name. I am not sure how to do this and if this if something you could help me with, but any input would be appreciated.

Thank you in advance!

Kind regards,

Cecile

**Comment by cfbuenabadn** [comment]
Thanks for raising this issue. I updated the code to deal with Ensembl IDs, and to avoid empty names of genes (this was causing your issue). I also added a few new optional parameters to deal with different names for the tags in the GTF file. You can check the updated README or pass the `--help` flag when running GTF2psix for details.

I uploaded a psix annotation using [Homo_sapiens.GRCh38.109.chr.gtf.gz](https://ftp.ensembl.org/pub/release-109/gtf/homo_sapiens/) from Ensembl to this repository, using the Ensembl ID instead of gene names. Feel free to use it. I created it using the following command:

`python sc_splicing_tools/GTF2psix.py --gtf Homo_sapiens.GRCh38.109.chr.gtf.gz -o psix_annotation --gene_type_tag gene_biotype --transcript_type_tag transcript_biotype`

I used the chromosomal annotation GTF. If you want to make an annotation with the entire Ensembl annotation, you can simply substitute the `--gtf` file for the Homo_sapiens.GRCh38.109.gtf.gz file. Right now the script is a bit slow (took me about 40 minutes to create the annotation), but hopefully you only have to run it once.

One more detail about this annotation: notice that GTF2psix will keep the original name of the chromosomes in your GTF. I.e., if your GTF file has chromosomes 1, 2, 3 instead of chr1, chr2, chr3, the Psix annotation will be the same. So the intron coordinates will look like this: 1:1486669-1487862:+ instead of chr1:1486669-1487862:+. Make sure that this is compatible with your SJ.out.tab files (it should be an easy fix if they're not).

Finally, the name of each AS event should now specify ProteinCoding, NMD, or other. ProteinCoding corresponds to events that are found in at least one transcript annotated as protein coding. NMD indicates events that do not occur in any protein coding transcripts, but they occur in at least one NMD transcript. Other corresponds to other annotations such as "processed transcript" or "retained intron". In my experience, these are usually unproductive transcripts and likely also NMD targets. 

Please let me know if you come across any other issues.
